//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCollectionCards
    {
        public int idcard { get; set; }
        public int fkperson { get; set; }
        public string cardname { get; set; }
        public byte mana { get; set; }
        public short attack { get; set; }
        public short life { get; set; }
        public int fkorder { get; set; }
        public int idcollectioncard { get; set; }
        public byte[] pic { get; set; }
    }
}
