//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSoldPacks
    {
        public int idorder { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> fkperson { get; set; }
        public Nullable<int> fkpack { get; set; }
        public int idpack { get; set; }
        public string packname { get; set; }
        public Nullable<decimal> packprice { get; set; }
        public int cardquantity { get; set; }
        public string picturename { get; set; }
        public int goldquantity { get; set; }
    }
}
